/* x = 180
console.log(x)
function lecText() {
    let x =18 
    //console.log(x)
    if (true) {
        x = 71;
        console.log(x);

    }
    console.log(x)
}
lecText()




console.log(x)*/
var person = {

    firstName: "John",
  
    lastName: "Doe"
  
  };
  
  alert(person.firstName);
  console.log(person.firstName)

  var persona = {
    name: "John",
    age: 50
    };
    alert(persona.name + " is " +persona.age )

    var frutas = ["Manzana", "Plátano", "Naranja"];

for (i=0;i<3;i++) {

  console.log(frutas[i]);

}
